export const CommonConstants = {
  EMAIL_SERVICE_NAME: "sendgrid",
  OTP_LENGTH: 5,
  OTP_VALIDATION_SECONDS: 10 * 60 * 1000,
  OTP_EMAIL_SUBJECT: "OTP Request",
  OTP_EMAIL_MESSAGE:
    "Please find the OTP %s. It has a validity of ten minutes.",
  RESET_PASSWORD_EMAIL_SUBJECT: "Reset your Password",
  RESET_PASSWORD_EMAIL_MESSAGE:
    "Please follow the link below to reset your password. \nLink to reset password: %s",
  JWT_TOKEN_SECRET_SIZE: 384,
  JWT_TOKEN_TYPE: "JWT",
  JWT_TOKEN_ALGORITHM: "HS384",
  ACCESS_TOKEN: "Access-Token",
  CHECKOUT_MODE_SUBSCRIPTION: "subscription",
  CHECKOUT_MODE_PAYMENT: "payment",
  STRIPE_SIGNATURE: "stripe-signature",
  PAYMENT_SERVICE_CUSTOMER_CREATED: "customer.created",
  PAYMENT_SERVICE_CUSTOMER_SUBSCRIPTION_CREATED:
    "customer.subscription.created",
  PAYMENT_SERVICE_INVOICE_PAID: "invoice.paid",
  PAYMENT_SERVICE_INVOIDCE_PAYMENT_FAILED: "invoice.payment_failed",
  PAYMENT_SERVICE_CUSTOMER_SUBSCRIPTION_UPDATED:
    "customer.subscription.updated",
  PAYMENT_SERVICE_CUSTOMER_SUBSCRIPTION_DELETED:
    "customer.subscription.deleted",
  SUBSCRIPTION_PLAN_TYPE_RECURRING: "recurring",
  SUBSCRIPTION_PLAN_TYPE_ONE_TIME: "one_time",
  CLIENT_TYPE_WEB: "web",
  CLIENT_TYPE_MOBILE: "mobile",
  REFRESH_TOKEN: "Refresh-Token",
  MULTER_BODY_IMAGE_KEY: "bodyImage",
  MULTER_FACE_IMAGE_KEY: "faceImage",
  GUEST_USER_TYPE: "guest_user",
  REGISTERED_USER_TYPE: "registered_user_type",
  ADMIN_USER_TYPE: "admin_user_type",
  ONLY_REGISTERED_USER_ACCESS: ["registered_user_type"],
  ONLY_GUEST_USER_ACCESS: ["guest_user"],
  ONLY_ADMIN_USER_ACCESS: ["admin_user_type"],
  ALL_USERS_ACCESS: ["registered_user_type", "guest_user", "admin_user_type"],
  CLIENT_TYPE: "client-type",
  BODY_PARSER_MAX_LIMIT: "100mb",
  NOT_BEFORE_BUFFER_TIME: 10,
  SUCCESS_STATUS: "success",
  FAILURE_STATUS: "failure",
};
